### PR TITLE
Create .npmignore

### PR DESCRIPTION
**Pull request by pkuczynski**

### CODE REVIEW

**Comment by mafintosh** [comment]
Thanks but I don’t use nomignores 😊

**Comment by pkuczynski** [comment]
So what do you use to exclude not needed files from the package? As your published package does include some not needed files...

**Comment by mafintosh** [comment]
I use the .gitignore for that. Adding an .npmignore means I have to keep those in sync manually which isn't really worth the overhead for me.

**Comment by pkuczynski** [comment]
`.gitignore` does not help in the case of `npm publish` as `npm` is not using `.gitignore`. Also, you might want to commit files in your repo but do not exclude them in the package. Hence `.npmignore` comes pretty handily. Otherwise, how would you like to exclude `.travis.yml` from npm package?

**Comment by mafintosh** [comment]
I don't personally, but yea that'd what you'd use the .npmignore for. Like I said just not worth the maintenance burden of keeping them in sync for the gain for me personally :)

**Comment by pkuczynski** [comment]
I don't really think that they have to be kept in sync tbh, especially for such a small package :) Especially in this case, `gitignore` contains only `node_modules` which is excluded by `npm` by default :)

I know it's minor optimization, yet it would be good to merge it, so the travis file does not have to be included in every docker image or serverless function, which is created based on some dependency to your package. Smaller package/image = faster download, less electricity used, less space, etc. So every .$ counts in making the planet a better place :)

One way or another, thank you for taking the time and reply to me :)

**Pull request closed without merging**
